      - name: Try original default password
        run: |
          keytool -list -v -keystore ks.keystore -storepass 123456789 \
            -storetype BKS \
            -providerclass org.bouncycastle.jce.provider.BouncyCastleProvider \
            -providerpath bcprov.jar
